// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQL0V3B_hnLvMk_dyBkGe80xWs2a4hiBM',
    appId: '1:192212297629:web:92257cfa51feae58c93174',
    messagingSenderId: '192212297629',
    projectId: 'fbchatapp-b75ba',
    authDomain: 'fbchatapp-b75ba.firebaseapp.com',
    storageBucket: 'fbchatapp-b75ba.appspot.com',
    measurementId: 'G-WL7FL09DLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvmmeuxUQHyFO75PkwuBiM3zrILwsO1Bw',
    appId: '1:192212297629:android:bf72d03a6f41df9fc93174',
    messagingSenderId: '192212297629',
    projectId: 'fbchatapp-b75ba',
    storageBucket: 'fbchatapp-b75ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBjaluGXXTG4qAUgJ7SdDvn0W54-nVns',
    appId: '1:192212297629:ios:65615ff6c124fe73c93174',
    messagingSenderId: '192212297629',
    projectId: 'fbchatapp-b75ba',
    storageBucket: 'fbchatapp-b75ba.appspot.com',
    iosBundleId: 'com.example.fbChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBjaluGXXTG4qAUgJ7SdDvn0W54-nVns',
    appId: '1:192212297629:ios:560bb1762b132393c93174',
    messagingSenderId: '192212297629',
    projectId: 'fbchatapp-b75ba',
    storageBucket: 'fbchatapp-b75ba.appspot.com',
    iosBundleId: 'com.example.fbChatApp.RunnerTests',
  );
}
